spring:
  application:
    name: EasyApply
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: *****
            clientSecret: *****

server:
  port: 9001
#Oauth2
